[pytest]
testpaths = intuition/tests
norecursedirs = .git .pytest_cache __pycache__ build dist github-clean-slate github-clean-slate-final pytest-of-ADMIN __testtmp
cache_dir = .pytest-tmp-runtime/pytest-cache
