"""Generate transcripts for lecture videos with open-source Whisper.

Why this lives between Retrieve and Push
----------------------------------------
The pipeline moves files: once a video is verified in Drive the local copy is deleted.
So transcription has to happen while the bytes are still on disk. Slot it after the
download and before the relay, and both the video and its transcript go up together.

Backend
-------
faster-whisper (CTranslate2) rather than openai-whisper: it needs no torch, runs int8 on
CPU at roughly 3-5x realtime, and decodes audio through bundled ffmpeg libs. Imported
lazily so the rest of the tool runs without it.

Output
------
Two files beside the video, both useful:
  <name>.vtt  - timed captions, playable in Drive's preview and any video player
  <name>.txt  - flat text, which is what actually makes a lecture searchable
"""
import os
from typing import Callable, Dict, List, Optional

VIDEO_EXTENSIONS = (
    ".mp4", ".mkv", ".mov", ".avi", ".wmv", ".flv", ".webm", ".m4v", ".mpg", ".mpeg",
)
AUDIO_EXTENSIONS = (".mp3", ".m4a", ".wav", ".aac", ".ogg", ".flac", ".wma")

DEFAULT_MODEL = "small.en"
# int8 is the reason this is usable without a GPU; float32 on CPU is ~4x slower for no
# meaningful accuracy gain at these model sizes.
DEFAULT_COMPUTE_TYPE = "int8"

# Formats a lecturer might upload as a real transcript, alongside our own output.
CAPTION_EXTENSIONS = (".vtt", ".srt", ".sbv", ".dfxp", ".ttml", ".sub", ".ass")
DOC_EXTENSIONS = (".txt", ".pdf", ".docx", ".doc", ".rtf", ".md")
TRANSCRIPT_WORDS = ("transcript", "caption", "subtitle", "subs")

# Stamped into the VTT header so a generated transcript can always be told apart from
# one the lecturer supplied. Without this the two are indistinguishable on disk, and we
# would either overwrite the lecturer's work or never refresh our own.
GENERATED_MARKER = "NOTE Generated by iNTUition"

# Transcript provenance
PROVIDED = "provided"    # the course supplied it - never overwrite, never regenerate
GENERATED = "generated"  # we made it with Whisper
MISSING = "missing"      # nothing exists


class TranscribeError(Exception):
    pass


INSTALL_HELP = (
    "Transcription needs faster-whisper:\n"
    "    pip install faster-whisper\n"
    "It bundles its own audio decoding, so no separate ffmpeg install is required."
)


def is_media(path: str) -> bool:
    return path.lower().endswith(VIDEO_EXTENSIONS + AUDIO_EXTENSIONS)


def transcript_paths(media_path: str) -> Dict[str, str]:
    """Where the transcript for a given media file belongs."""
    stem, _ext = os.path.splitext(media_path)
    return {"vtt": stem + ".vtt", "txt": stem + ".txt"}


def already_transcribed(media_path: str) -> bool:
    p = transcript_paths(media_path)
    return os.path.exists(p["vtt"]) and os.path.exists(p["txt"])


def is_generated(path: str) -> bool:
    """True if this transcript file carries our provenance marker."""
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return GENERATED_MARKER in f.read(400)
    except OSError:
        return False


def _is_transcript_name(name: str, stem_low: str) -> bool:
    """Does ``name`` look like a transcript belonging to a media file named ``stem_low``?

    Two shapes are accepted, matching how lecturers actually upload them:
      * same stem, caption extension     - "Lecture 1.mp4" + "Lecture 1.vtt"
      * a neighbour naming the media and saying transcript, in any doc format
        - "Lecture 1 transcript.docx", "Transcript - Lecture 1.pdf"

    Shared between the local check (``find_existing_transcripts``, real files on
    disk) and the Drive check (``_drive_transcript_status``, just a set of sibling
    names from a Drive listing) so "what counts as a transcript" stays one rule.
    """
    low = name.lower()
    base, ext = os.path.splitext(low)
    if base == stem_low and ext in CAPTION_EXTENSIONS + (".txt",):
        return True
    return bool(
        ext in CAPTION_EXTENSIONS + DOC_EXTENSIONS
        and any(w in low for w in TRANSCRIPT_WORDS)
        and (stem_low in low or low.replace("transcript", "").strip(" -_.") in stem_low)
    )


def find_existing_transcripts(media_path: str) -> List[str]:
    """Transcript-ish files that appear to belong to this media file."""
    directory = os.path.dirname(media_path) or "."
    stem_low = os.path.splitext(os.path.basename(media_path))[0].lower()
    hits: List[str] = []

    try:
        entries = os.listdir(directory)
    except OSError:
        return hits

    for name in entries:
        full = os.path.join(directory, name)
        if not os.path.isfile(full) or full == media_path:
            continue
        if _is_transcript_name(name, stem_low):
            hits.append(full)

    return sorted(set(hits))


def transcript_status(media_path: str) -> Dict:
    """Classify a media file: does a transcript already exist, and who made it?

    A lecturer-supplied transcript wins outright - there is no point burning CPU to
    produce a worse copy of something the course already gives you.
    """
    existing = find_existing_transcripts(media_path)
    ours = transcript_paths(media_path)

    provided = [
        p for p in existing
        if not (os.path.normcase(p) == os.path.normcase(ours["vtt"]) and is_generated(p))
        and not (os.path.normcase(p) == os.path.normcase(ours["txt"])
                 and os.path.exists(ours["vtt"]) and is_generated(ours["vtt"]))
    ]

    if provided:
        return {"status": PROVIDED, "sources": provided}
    if os.path.exists(ours["vtt"]) and is_generated(ours["vtt"]):
        return {"status": GENERATED, "sources": [ours["vtt"], ours["txt"]]}
    return {"status": MISSING, "sources": []}


def survey(root: str) -> List[Dict]:
    """Every staged media file with its transcript provenance.

    This is what the UI needs in order to ask rather than assume: it can show which
    lectures already come with a transcript and let the user pick only the rest.
    """
    out: List[Dict] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for name in sorted(filenames):
            if name.startswith("."):
                continue
            full = os.path.join(dirpath, name)
            if not is_media(full):
                continue
            info = transcript_status(full)
            out.append({
                "path": full,
                "rel_path": os.path.relpath(full, root),
                "name": name,
                "size": os.path.getsize(full) if os.path.exists(full) else 0,
                "status": info["status"],
                "sources": [os.path.basename(s) for s in info["sources"]],
            })
    return sorted(out, key=lambda e: e["rel_path"])


def _drive_transcript_status(siblings: Dict[str, Dict], media_name: str) -> Dict:
    """``transcript_status()`` for a file that lives in Drive, not on disk.

    There is no local directory to list, so the caller supplies what it already
    has - the other files in the same Drive folder, keyed by name. This can't check
    a Drive ``.vtt``'s content for the GENERATED_MARKER the way ``is_generated``
    does for a local file without downloading it just to look, so it takes a
    same-named vtt+txt pair as our own output on trust - nothing else predictably
    produces both, and a false positive here only means skipping a re-transcribe,
    never overwriting anything.
    """
    stem_low = os.path.splitext(media_name)[0].lower()
    ours = transcript_paths(media_name)
    ours_vtt, ours_txt = ours["vtt"], ours["txt"]
    # Only a complete, exactly-named pair is trusted as our own output - a lone vtt
    # (even one that happens to share our naming convention) is exactly what a
    # lecturer who skips the .txt looks like, and Whisper never writes one file
    # without the other, so PROVIDED is the safe read for it.
    if ours_vtt in siblings and ours_txt in siblings:
        return {"status": GENERATED, "sources": [ours_vtt, ours_txt]}
    provided = [name for name in siblings if _is_transcript_name(name, stem_low)]
    if provided:
        return {"status": PROVIDED, "sources": provided}
    return {"status": MISSING, "sources": []}


def classify_drive_media(files: List[Dict]) -> List[Dict]:
    """Media already archived in Drive, with transcript provenance - survey()'s
    counterpart for files move mode has already deleted the local copy of.

    ``files`` is an already-fetched flat listing shaped like
    ``drive.DriveMirror.list_files()`` (id, name, rel_path, mime_type, size,
    modified) - typically the dashboard's own cached Drive index, or one
    ``transcribe_run.py --backfill`` fetches itself. This never talks to Drive on
    its own, so calling it costs nothing beyond whatever already produced
    ``files``. Detection only: pulling a result back, transcribing it, and
    uploading the output is ``transcribe_run.py --backfill``, not this function.
    """
    by_dir: Dict[str, Dict[str, Dict]] = {}
    for f in files:
        directory = os.path.dirname(f.get("rel_path") or "")
        by_dir.setdefault(directory, {})[f["name"]] = f

    out: List[Dict] = []
    for f in files:
        if not is_media(f["name"]):
            continue
        directory = os.path.dirname(f.get("rel_path") or "")
        siblings = by_dir.get(directory, {})
        info = _drive_transcript_status(siblings, f["name"])
        out.append({
            "drive_id": f["id"],
            "rel_path": f.get("rel_path") or f["name"],
            "name": f["name"],
            "size": int(f.get("size") or 0),
            "modified": f.get("modified"),
            "status": info["status"],
            "sources": info["sources"],
            "location": "drive",
        })
    return sorted(out, key=lambda e: e["rel_path"].lower())


def _timestamp(seconds: float) -> str:
    """WebVTT wants HH:MM:SS.mmm."""
    if seconds < 0:
        seconds = 0
    ms = int(round(seconds * 1000))
    h, ms = divmod(ms, 3_600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1000)
    return "{:02d}:{:02d}:{:02d}.{:03d}".format(h, m, s, ms)


def to_vtt(segments: List[Dict], model: Optional[str] = None) -> str:
    # A NOTE block is legal WebVTT header content and is ignored by players, so it is a
    # safe place to record that this file is machine-generated.
    lines = ["WEBVTT", ""]
    lines.append("{} (Whisper {})".format(GENERATED_MARKER, model or DEFAULT_MODEL))
    lines.append("NOTE Machine transcription - may contain errors.")
    lines.append("")
    for seg in segments:
        lines.append(
            "{} --> {}".format(_timestamp(seg["start"]), _timestamp(seg["end"]))
        )
        lines.append(seg["text"].strip())
        lines.append("")
    return "\n".join(lines)


def to_text(segments: List[Dict]) -> str:
    """Flat prose, wrapped loosely so the file is readable rather than one long line."""
    body = " ".join(seg["text"].strip() for seg in segments).strip()
    out, line = [], ""
    for word in body.split():
        if len(line) + len(word) + 1 > 100:
            out.append(line)
            line = word
        else:
            line = (line + " " + word).strip()
    if line:
        out.append(line)
    return "\n".join(out) + "\n"


class Transcriber:
    """Holds one loaded Whisper model across many files.

    Loading costs seconds and a few hundred MB, so reuse one instance for a whole run.
    """

    def __init__(
        self,
        model_name: str = DEFAULT_MODEL,
        compute_type: str = DEFAULT_COMPUTE_TYPE,
        device: str = "auto",
        cpu_threads: int = 0,
    ):
        self.model_name = model_name
        self.compute_type = compute_type
        self.device = device
        self.cpu_threads = cpu_threads
        self._model = None

    def load(self):
        if self._model is not None:
            return self._model
        try:
            from faster_whisper import WhisperModel
        except ImportError as e:
            raise TranscribeError("{}\n({})".format(INSTALL_HELP, e))
        self._model = WhisperModel(
            self.model_name,
            device=self.device,
            compute_type=self.compute_type,
            cpu_threads=self.cpu_threads,
        )
        return self._model

    def transcribe(
        self,
        media_path: str,
        progress: Optional[Callable[[float, str], None]] = None,
    ) -> Dict[str, str]:
        """Transcribe one file and write .vtt/.txt beside it. Returns the written paths."""
        if not os.path.isfile(media_path):
            raise TranscribeError("Not on disk: {}".format(media_path))

        model = self.load()
        segments_iter, info = model.transcribe(
            media_path,
            beam_size=5,
            # Silence-skipping cuts a lot of dead air out of lecture recordings.
            vad_filter=True,
            vad_parameters={"min_silence_duration_ms": 500},
        )

        total = float(getattr(info, "duration", 0) or 0)
        segments: List[Dict] = []
        for seg in segments_iter:
            segments.append({"start": seg.start, "end": seg.end, "text": seg.text})
            if progress and total:
                progress(min(1.0, seg.end / total), seg.text.strip()[:60])

        if not segments:
            raise TranscribeError("No speech detected in {}".format(
                os.path.basename(media_path)))

        paths = transcript_paths(media_path)
        with open(paths["vtt"], "w", encoding="utf-8") as f:
            f.write(to_vtt(segments, model=self.model_name))
        with open(paths["txt"], "w", encoding="utf-8") as f:
            f.write(to_text(segments))
        return paths


def find_media(root: str, skip_transcribed: bool = True) -> List[str]:
    """Staged media that has no transcript from any source.

    Excludes anything the course already supplies a transcript for, not just what we
    have generated before - running Whisper over a lecturer's own transcript would
    waste CPU and produce a worse copy.
    """
    return [
        e["path"] for e in survey(root)
        if not skip_transcribed or e["status"] == MISSING
    ]
